"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
auto_upgrade = true
console_title_template = "{{if .Root}}Admin: {{end}} {{.Folder}}"
version = 2

[palette]
os = "#acb0be"
closer = "#d3d7cf"
foreground = "p:base"
rosewater = "#f4dbdd6"
pink = "#f5bde6"
mauve = "#c6a0f5"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext = "#a5adcb"
base = "#23273a"
crust = "#181926"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "p:text"
  foreground = "p:base"
  leading_diamond = "╭─"
  style = "diamond"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"

  [[blocks.segments]]
  background = "p:blue"
  foreground = "p:base"
  powerline_symbol = ""
  style = "powerline"
  template = "  {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    home_icon = "~"
    style = "agnoster_short"
    hide_root_location = true
    max_depth = 3

  [[blocks.segments]]
  background = "p:green"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
    "{{ if gt .Ahead 0 }}p:sky{{ end }}",
    "{{ if gt .Behind 0 }}p:mauve{{ end }}"
  ]
  foreground = "p:base"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "p:peach"
  foreground = "p:crust"
  invert_powerline = true
  powerline_symbol = ""
  style = "powerline"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  "
  type = "python"

  [[blocks.segments]]
  background = "p:yellow"
  foreground = "p:crust"
  invert_powerline = true
  powerline_symbol = ""
  style = "powerline"
  template = "  "
  type = "root"

  [[blocks.segments]]
  background = "p:base"
  background_templates = [ "{{ if gt .Code 0 }}p:red{{ end }}" ]
  foreground = "p:green"
  foreground_templates = [ "{{ if gt .Code 0 }}p:base{{ end }}" ]
  invert_powerline = true
  powerline_symbol = ""
  style = "powerline"
  template = " {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} "
  type = "status"

    [blocks.segments.properties]
    always_enabled = true

  [[blocks.segments]]
  background = "p:text"
  foreground = "p:base"
  invert_powerline = true
  style = "diamond"
  template = " {{ .CurrentDate | date .Format }}  "
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05 | Jan 2"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "p:text"
  style = "plain"
  template = "╰─"
  type = "text"

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  background = "p:lavender"
  foreground = "p:base"
  invert_powerline = true
  powerline_symbol = ""
  style = "powerline"
  template = " {{ round .PhysicalPercentUsed .Precision}}%  "
  type = "sysinfo"
  
    [blocks.segments.properties]
    precision = 2

  [[blocks.segments]]
  background = "p:maroon"
  foreground = "p:base"
  invert_powerline = true
  # leading_diamond = ""
  style = "diamond"
  template = " {{ .FormattedMs }}  "
  type = "executiontime"

    [blocks.segments.properties]
    always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "p:text"
template = "╰─"

