console_title_template = '{{if .Root}}Admin: {{end}} {{.Folder}}'
version = 3
auto_upgrade = true
final_space = true

[palette]
  base = '#23273a'
  blue = '#8aadf4'
  closer = '#d3d7cf'
  crust = '#181926'
  foreground = 'p:base'
  green = '#a6da95'
  lavender = '#b7bdf8'
  maroon = '#ee99a0'
  mauve = '#c6a0f5'
  os = '#acb0be'
  peach = '#f5a97f'
  pink = '#f5bde6'
  red = '#ed8796'
  rosewater = '#f4dbdd6'
  sapphire = '#7dc4e4'
  sky = '#91d7e3'
  subtext = '#a5adcb'
  teal = '#8bd5ca'
  text = '#cad3f5'
  yellow = '#eed49f'

[transient_prompt]
  template = '╰─'
  foreground = 'p:text'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = '╭─'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = 'p:base'
    background = 'p:text'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      hide_root_location = false
      home_icon = '~'
      max_depth = 3
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:sky{{ end }}', '{{ if gt .Behind 0 }}p:mauve{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    foreground = 'p:green'
    powerline_symbol = ''
    background = 'p:base'
    type = 'status'
    style = 'powerline'
    foreground_templates = ['{{ if gt .Code 0 }}p:base{{ end }}']
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = 'p:crust'
    powerline_symbol = ''
    background = 'p:peach'
    type = 'python'
    style = 'powerline'
    invert_powerline = true

  [[blocks.segments]]
    template = '  '
    foreground = 'p:crust'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'root'
    style = 'powerline'
    invert_powerline = true

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = 'p:base'
    background = 'p:text'
    type = 'time'
    style = 'diamond'
    invert_powerline = true

    [blocks.segments.properties]
      time_format = '15:04:05 | Jan 2'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = 'p:text'
    type = 'text'
    style = 'plain'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' {{ round .PhysicalPercentUsed .Precision}}%  '
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:lavender'
    type = 'sysinfo'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      precision = 2

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}  '
    foreground = 'p:base'
    background = 'p:maroon'
    type = 'executiontime'
    style = 'diamond'
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true
