# Set color scheme
colorscheme rose-pine-moon

# Tab width/Indent width
set-option global tabstop 4
set-option global indentwidth 4


# Line numbers
add-highlighter global/ number-lines -relative -hlcursor

# Matching braces
add-highlighter global/ show-matching

# Trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Unselect on escape
map global normal <esc> ";,"

# Comment lines
map global normal <c-v> ":comment-line<ret>"

# Go through buffers with <space>m/n
map -docstring "goto previous buffer" global user n ": bp<ret>"
map -docstring "goto next buffer" global user m ": bn<ret>"

# Copy to clipboard
map -docstring "copy to system pboard" global user y "<a-|> pbcopy<ret>"

# Clippy is now cat
set-option global ui_options terminal_assistant=cat

# Tabs for autocomplete
hook global InsertCompletionShow .* %{
  try %{
    # this command temporarily removes cursors preceded by whitespace;
    # if there are no cursors left, it raises an error, does not
    # continue to execute the mapping commands, and the error is eaten
    # by the `try` command so no warning appears.
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
    hook -once -always window InsertCompletionHide .* %{
      unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
    }
  }
}

### Plugins

# Ensure plug.kak is installed and loaded
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload
