# Set color scheme
colorscheme rose-pine-moon

# Tab width/Indent width
set-option global tabstop 4
set-option global indentwidth 4

# Line numbers
add-highlighter global/ number-lines -relative -hlcursor -separator '  '

# Matching braces
add-highlighter global/ show-matching

# Trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Unselect on escape
map global normal <esc> ";,"

# Comment lines
map global normal '#' ":comment-line<ret>"

# Evaluate math (from mawww's config)
map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'

# Go through buffers with <space>m/n
map -docstring "goto previous buffer" global user n ": bp<ret>"
map -docstring "goto next buffer" global user m ": bn<ret>"

# Copy to clipboard
map -docstring "copy to system pboard" global user y "<a-|> pbcopy<ret>"

# Clippy is now cat
set-option global ui_options terminal_assistant=cat

# Tabs for autocomplete
hook global InsertCompletionShow .* %{
  try %{
    # this command temporarily removes cursors preceded by whitespace;
    # if there are no cursors left, it raises an error, does not
    # continue to execute the mapping commands, and the error is eaten
    # by the `try` command so no warning appears.
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
    hook -once -always window InsertCompletionHide .* %{
      unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
    }
  }
}

# Cursor Color in Insert Mode
# TODO: change to use colorscheme-native colors

# Shades of blue/cyan for normal mode
set-face global PrimarySelection black,cyan+F
set-face global SecondarySelection black,blue+F
set-face global PrimaryCursor black,bright-cyan+F
set-face global SecondaryCursor black,bright-blue+F
set-face global PrimaryCursorEol black,bright-cyan
set-face global SecondaryCursorEol black,bright-blue

# Shades of green/yellow for insert mode.
hook global ModeChange (push|pop):.*:insert %{
    set-face window PrimarySelection black,yellow+F
    set-face window SecondarySelection black,green+F
    set-face window PrimaryCursor black,bright-yellow+F
    set-face window SecondaryCursor black,bright-green+F
    set-face window PrimaryCursorEol black,bright-yellow
    set-face window SecondaryCursorEol black,bright-green
}

# Undo colour changes when we leave insert mode.
hook global ModeChange (push|pop):insert:.* %{
    unset-face window PrimarySelection
    unset-face window SecondarySelection
    unset-face window PrimaryCursor
    unset-face window SecondaryCursor
    unset-face window PrimaryCursorEol
    unset-face window SecondaryCursorEol
}

### Plugins

# Ensure plug.kak is installed and loaded
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

# fzf
# plug "andreyorst/fzf.kak" config %{
#     require-module fzf
#     require-module fzf-grep
#     require-module fzf-file
# } defer fzf %{
#     set-option global fzf_highlight_command "bat -r {}"
# } defer fzf-file %{
#     set-option global fzf_file_command "fd . --no-ignore-vcs"
# } defer fzf-grep %{
#     set-option global fzf_grep_command "rg"
# }

# map -docstring "open fzf" global user f ": fzf-mode<ret>"

# powerline
plug "andreyorst/powerline.kak" defer powerline_palenight %{
    powerline-theme palenight
} defer powerline %{
	powerline-format global "mode_info git bufname filetype line_column position"
	set-option global powerline_separator_thin ""
	set-option global powerline_separator ""
} config %{
	powerline-start
}

plug 'delapouite/kakoune-mirror' %{
# Suggested mapping
  map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

plug "gustavo-hms/luar" %{
    require-module luar
}

plug "gustavo-hms/peneira" %{
    require-module peneira
}

define-command peneira-buffers %{
    peneira 'buffers: ' %{ eval "printf '%s\n' $kak_quoted_buflist" } %{
        buffer %arg{1}
    }
}

map -docstring "open peneira buffers" global user b ": peneira-buffers<ret>"

# Buffer management
plug 'delapouite/kakoune-buffers' %{
    # use qwe for navigation, and b for buffers
    map global normal ^ q
    map global normal <a-^> Q
    map global normal q b
    map global normal Q B
    map global normal <a-q> <a-b>
    map global normal <a-Q> <a-B>
    map global normal b ': enter-buffers-mode<ret>' -docstring 'buffers'
    map global normal B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
}

